### GENERAL SETTINGS ###

# Site settings
title: ReductStore
description: Time series precision supercharges blob data at unmatched speed and vast scale – setting the benchmark for edge computing, computer vision, and IoT.
analytics: G-Y51RZRPE3X
baseurl: "" #important: start with /
url: "https://www.reduct.store"

# Build settings
markdown: kramdown


# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  highlighter: rouge

permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

projects:
  reductstore:
    version: v1.5.1

colors: #in hex code if not noted else
  primary: "#2B0548" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  success: "#22ad24"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/reductstore
  - title: twitter
    url: https://twitter.com/ReductStore
  - title: linkedin
    url: https://www.linkedin.com/company/reductstore
  - title: discord
    url: https://discord.gg/8wPtPGJYsn

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - 651 N BROAD ST STE 201
  - MIDDLETOWN, DE 19709
email: info@reduct.store


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: |
  ReductStore is a time series database designed specifically for storing and managing large amounts of blob data. 
  It has high performance for writing and real-time querying, making it suitable for edge computing, computer vision, and IoT applications.
  ReductStore is 100% open source under Mozilla Public License 2.0.


plugins:
  - jemoji
  - jekyll-seo-tag

twitter:
  username: ReductStore
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: assets/img/logo_default.jpg
