### GENERAL SETTINGS ###

# Site settings
title: Reduct Storage
description: A time series database for big data
analytics: G-Y51RZRPE3X
baseurl: "" #important: start with /
url: "https://reduct-storage.dev"

# Build settings
markdown: kramdown


# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  highlighter: rouge

permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#231b49" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  success: "#22ad24"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/reduct-storage
  - title: twitter
    url: https://twitter.com/ReductStorage
  - title: discord
    url: https://discord.gg/NQbPeGgzdR

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
      - Hamburg, Germany
email: atimin@gmail.com


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Alexey Timin
    position: Creator
    text: C++\Python Developer
    #    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:atimin@gmail.com
#      - title: twitter
#        url: http://twitter.com/handle
#  - name: Paul Jameson
#    position: Lead Designer
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team02.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle
#  - name: Laura Sommers
#    position: Lead Developer
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team03.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle
#  - name: Martin Blunt
#    position: Marketing
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team04.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
#clients:
#  - name: dribbble
#    img: client01.png
#  - name: Code is Poetry
#    img: client02.png
#  - name: Vimeo
#    img: client03.png
#  - name: VimeoPro
#    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: |
  Reduct Storage is a time series database for big data. It has no limitation on the size of stored objects.
  It provides a simple HTTP API and is optimized for random data reads via a timestamp or larger chunks via time intervals.

# Testimonial content. Shown on Home and About page.
#testimonial:
#    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
#    author: Marcel Newman
#    position: WEB DESIGNER - BLACKTIE.CO


plugins:
  - jemoji
  - jekyll-seo-tag

twitter:
  username: ReductStorage
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: assets/img/logo_default.jpg
